### ISSUE TITLE
Questions About How to Train this repo

### ISSUE THREAD

**Issue by sudeakinay** [zhiqic/Rethinking-Counting#3]
# Some Questions About How to Train this repo

I have been having some errors with the following files:

*  **models/backbone/train.py**
* **models/backbone/trainer.py**
* **config.py**

	* on `models/backbone/train.py` :
	what is the "seed" expression between lines 8 and 11 written for?
	On line 43, when the code enters `models/backbone/trainer.py`,  I get an "NameError: name "CrowdCounter" is not defined" error.

	* on `models/backbone/trainer.py` :
	the reason I am getting the name error in the `models/backbone/train.py`  is the CrowdCounter function written on line 24 in this file, but it actually does not exist anywhere. Or at least I couldn`t find it.

		I cannot import cfg_data from the `dataset.WE.setting` specified on line 159. Because there is no such file in the specified dataset folder. Could the specified library be something other than WE? (such as SSHA, SSHB, UCF50 etc)

	* on `config.py` :
	On line 19: `__C.NET = "Res50_SFCN" # net selection MCNN, Res50, CSRNet, SANet` is written but I get an error because of the selected net, which is Res50_SFCN. Is it a problem if I use the network that I choose, not the default one?

---
## Thanks in advance for all of your answers! 
By the way,  Although I have only just begun to interested in crowd counting analysis as a 3rd year student of electronics and communication engineering, I really enjoyed your paper and repository. 👍🏼

**Comment by zhiqic** [comment]
Thanks for pointing out the problem with the backbone. We'll check and fix it asap.

**Comment by zhiqic** [comment]
So far, the TensorFlow+CUDA version is very redundant and complex due to ablation experiments and heavy reliance on existing code repositories. We are reproducing a Pytorch version. We will release the PyTorch version soon.

**Comment by zhiqic** [comment]
Thank you for your problem is solved.
