### ISSUE TITLE
When the pytorch version is completed

### ISSUE THREAD

**Issue by yishun-Liu** [zhiqic/Rethinking-Counting#5]
Hello, the author and everyone, I want to konw when the pytorch version will be completed, thanks very much.

**Comment by zhiqic** [comment]
We've been preparing a PyTorch version. But one of the code bases we originally adopted does not support PyTorch (http://box.vicos.si/skokec/dau-convnet). This gives us a lot of resistance.

**Comment by zhiqic** [comment]
We have an implementation that is not based on this repository. But the performance is not up to now. We're trying to fix it.

**Comment by yishun-Liu** [comment]
Thank you for your reply. That sounds bad. It's a lot of work. I wish you a quick fix and look forward to your Pytorch version of the model.

**Comment by JNaranjo-Alcazar** [comment]
Hello, has the pytorch version been implemented?

Thanks in advance
