### ISSUE TITLE
NameError: name 'CrowdCounter' is not defined

### ISSUE THREAD

**Issue by bekhzod-olimov** [zhiqic/Rethinking-Counting#7]
When I tried to run the train script (models/backbone/train.py) there is an error that the train script cannot find CrowdCounter function. Can you please tell how to define this function? Because without this file the code cannot be run.

**Comment by zhiqic** [comment]
We are sorry that we have modified some functions to facilitate the testing of the  PyTorch version. We'll be releasing the PyTorch implementation next week.
